// Copyright (c) Microsoft Corporation. All rights reserved.
// SPDX-License-Identifier: MIT

// Wifi
#define IOT_CONFIG_WIFI_SSID "chathushka"
#define IOT_CONFIG_WIFI_PASSWORD "87654321"

// Enable macro IOT_CONFIG_USE_X509_CERT to use an x509 certificate to authenticate the IoT device.
// The two main modes of authentication are through SAS tokens (automatically generated by the
// sample using the provided device symmetric key) or through x509 certificates. Please choose the
// appropriate option according to your device authentication mode.

// #define IOT_CONFIG_USE_X509_CERT

#ifdef IOT_CONFIG_USE_X509_CERT

/*
 * Please set the define IOT_CONFIG_DEVICE_CERT below with
 * the content of your device x509 certificate.
 *
 * Example:
 * #define IOT_CONFIG_DEVICE_CERT "-----BEGIN CERTIFICATE-----\r\n" \
 * "MIIBJDCBywIUfeHrebBVa2eZAbouBgACp9R3BncwCgYIKoZIzj0EAwIwETEPMA0G\r\n" \
 * "A1UEAwwGRFBTIENBMB4XDTIyMDMyMjazMTAzN1oXDTIzMDMyMjIzMTAzN1owGTEX\r\n" \
 * "MBUGA1UEAwwOY29udG9zby1kZXZpY2UwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC\r\n" \
 * .......
 * "YmGzdaHTb6P1W+p+jmc+jJn1MAoGCXqGSM49BAMCA0gAMEUCIEnbEMsAdGFroMwl\r\n" \
 * "vTfQahwsxN3xink9z1gtirrjQlqDAiEAyU+6TUJcG6d9JF+uJqsLFpsbbF3IzGAw\r\n" \
 * "yC+koNRC0MU=\r\n" \
 * "-----END CERTIFICATE-----"
 *
 */
#define IOT_CONFIG_DEVICE_CERT "Device Certificate"

/*
 * Please set the define IOT_CONFIG_DEVICE_CERT_PRIVATE_KEY below with
 * the content of your device x509 private key.
 *
 * Example:
 *
 * #define IOT_CONFIG_DEVICE_CERT_PRIVATE_KEY "-----BEGIN EC PRIVATE KEY-----\r\n" \
 * "MHcCAQEEIKGXkMMiO9D7jYpUjUGTBn7gGzeKPeNzCP83wbfQfLd9obAoGCCqGSM49\r\n" \
 * "AwEHoUQDQgAEU6nQoYbjgJvBwaeD6MyAYmOSDg0QhEdyyV337qrlIbDEKvFsn1El\r\n" \
 * "yRabc4dNp2Jhs3Xh02+j9Vvqfo5nPoyZ9Q==\r\n" \
 * "-----END EC PRIVATE KEY-----"
 *
 * Note the type of key may different in your case. Such as BEGIN PRIVATE KEY
 * or BEGIN RSA PRIVATE KEY.
 *
 */
#define IOT_CONFIG_DEVICE_CERT_PRIVATE_KEY "Device Certificate Private Key"

#endif // IOT_CONFIG_USE_X509_CERT

/*
// Azure IoT Hub1
#define IOT_CONFIG_IOTHUB_FQDN "iot-test-iothub-oversight-eastus2.azure-devices.net"
#define IOT_CONFIG_DEVICE_ID "ovs-device-new-plug-098"
// Use device key if not using certificates
#ifndef IOT_CONFIG_USE_X509_CERT
#define IOT_CONFIG_DEVICE_KEY "MOBBbYW2PotJoj9Tf1DjPg=="
#endif // IOT_CONFIG_USE_X509_CERT
*/
// HostName=dev-iothub-oversight-central-us.azure-devices.net;DeviceId=ovs-smart-plug-0011;SharedAccessKey=+yDr3TKSvU8yExQIeuvpHGd+//y9/WwAuS1Qcn1UI5E=
// Azure IoT Hub2
//"HostName=dev-iothub-oversight-central-us.azure-devices.net;DeviceId=ovs-smart-plug-0035;SharedAccessKey=Q+pXXoaXhylQsjsZjZboNw=="
#define IOT_CONFIG_IOTHUB_FQDN "dev-iothub-oversight-central-us.azure-devices.net" 
#define IOT_CONFIG_DEVICE_ID "athom-ac-controller-002"
// Use device key if not using certificates HostName=fyp-iothub-oversight-southeastasia.azure-devices.net;DeviceId=fyp-smart-plug-00011;SharedAccessKey=4SzGPezWib8/C3m5osJKPw==
#ifndef IOT_CONFIG_USE_X509_CERT
#define IOT_CONFIG_DEVICE_KEY "7zBiOJnvADOZ7iFyAxAXsg=="
#endif // IOT_CONFIG_USE_X509_CERT

/*
// Azure IoT Preview
#define IOT_CONFIG_IOTHUB_FQDN "fyp-iothub-oversight-southeastasia.azure-devices.net"
#define IOT_CONFIG_DEVICE_ID "OVPS_001"
# HostName=dev-iothub-oversight-central-us.azure-devices.net;DeviceId=OVS-G1-D0001;SharedAccessKey=0KMrxMazVp3vZNj8fNS35g==
// Use device key if not using certificates
#ifndef IOT_CONFIG_USE_X509_CERT
#define IOT_CONFIG_DEVICE_KEY "fRMmq/IoSk5fKMbxdyuif9ntgvx03LvmcF37MN0am9Y="
#endif // IOT_CONFIG_USE_X509_CERT
*/


// Publish 1 message every 2 seconds
#define TELEMETRY_FREQUENCY_MILLISECS 30000
